Add db schema
nussucommit/finsec-backend pull request #3
Opened 2022-02-06 03:00 UTC by EricBryann

2022-02-13 17:32 UTC, kevinmingtarja requested changes
Most of it looks good alrdy, thanks @EricBryann !

cc: @radiankrisno @ThePrevailingOne @zunedz to discuss the comments

2022-02-13 17:32 UTC, kevinmingtarja commented on db_schema.sql
> +	approvers		TEXT --NOT SURE (I think we dont need this?)
@radiankrisno is the `approver(s)` in this case the particular `role` who is allowed to approve? Because I see that in the [activity diagram](https://docs.google.com/document/d/1PzafHkjYhjHtApXm8sNKYDuj9j3ae1rzZ-_mxwz5oD4/edit#), there are 3 `approve` actions, all with different `roles` (`Finance Exec`, `Finance Secretary`, and `NUSSU President`.

cc: @ThePrevailingOne @zunedz

2022-02-13 17:32 UTC, kevinmingtarja commented on db_schema.sql
> +	salt			TEXT,
I think we don't need to store the `salt` in our db. We can follow this implementation for hashing the password: https://medium.com/@jcox250/password-hash-salt-using-golang-b041dc94cb72

2022-02-13 17:32 UTC, kevinmingtarja commented on db_schema.sql
> +	subcomms		TEXT, -- not sure
@radiankrisno I don't think we need this? I don't see any use for it so far. Because the only person where the `subcomms` are relevant is only `Finance Secretary` right?

cc: @ThePrevailingOne @zunedz

2022-02-13 17:32 UTC, kevinmingtarja commented on db_schema.sql
> +	quotation_id		INT, -- NO NEED PRIMARY KEY FOR THIS?
I think it's intended for `quotation_id` to be a primary key as well. Because an instance of `supplier` is only valid for a particular `quotation` and `item`, since it contains `unit_price` as well. So different items -> different quotations -> different supplier instance.

2022-02-13 17:32 UTC, kevinmingtarja commented on db_schema.sql
> +	suppliers			TEXT, -- NO NEED THIS?
I think it's still needed, because the quotation that we base this on is [the following](https://docs.google.com/spreadsheets/d/16wgc1mzy0EzLOqjOwE1-xUxvFE15XAl2/edit#gid=272197549). And here, when the requester fills up the form, they have to list down all the suppliers for reference.

2022-02-20 03:57 UTC, radiankrisno commented on db_schema.sql
> +	approvers		TEXT --NOT SURE (I think we dont need this?)
Yup this one should be the role who are able to approve only!

2022-02-20 03:58 UTC, radiankrisno commented on db_schema.sql
> +	subcomms		TEXT, -- not sure
Yup, no need we can just differentiate the approvers based on their role

2022-03-06 16:10 UTC, kevinmingtarja approved these changes
LGTM!

2022-03-06 16:10 UTC, kevinmingtarja commented on db_schema.sql
> +	approvers		TEXT --NOT SURE (I think we dont need this?)
okay we can delete the `approvers` field then since there's a relation just for this already.

2022-03-06 16:10 UTC, merged